version: "3"
services:
    figicore-api:
      container_name: figicore-api
      image: ghcr.io/nguyenchiemdu/figicore-api:latest
      restart: always
      ports:
        - "${PORT}:${PORT}"
      environment:
        - TZ=Asia/Ho_Chi_Minh
      env_file:
        - .env
      command: sh -c "npx prisma migrate deploy && npm run typeorm:migrate && node dist/main"
      # volumes:
      #   - ./uploads:/usr/src/app/uploads
      network_mode: host
