-- AlterTable
ALTER TABLE "product_variants" ADD COLUMN     "height_cm" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "length_cm" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "weight_g" INTEGER NOT NULL DEFAULT 200,
ADD COLUMN     "width_cm" INTEGER NOT NULL DEFAULT 10;
